routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::group(['prefix' => '/demo','namespace' => '\App\Http\Controllers'], function () {
    Route::get('/', 'SiteController@renderHomePage');
    Route::get('/services', 'SiteController@renderServicesPage');
    Route::get('/articles/{cgy}', 'SiteController@renderCgyArticlesPage');
    Route::get('/article/{article}', 'SiteController@renderArticlePage');
    Route::get('/about', 'SiteController@renderAboutPage');
    Route::get('/contact', 'SiteController@renderContactPage');
    Route::get('/thank', 'SiteController@renderThankPage');
    Route::get('/policy', 'SiteController@renderPolicyPage');
    Route::get('/portfolio','SiteController@renderPortfolioPage');
    Route::get('/portfolio/{media}', 'SiteController@renderPortfolioDetailPage');
    Route::post('/save','SiteController@save');
});



Route::get('/','\App\Http\Controllers\SiteController@renderWelcomePage');


//自定義後台路由規則
Route::group(['prefix' => 'admin', 'namespace' => '\App\Http\Controllers', 'middleware' => ['web', 'javck.roleCheck', 'javck.verifyEnabled']], function () {
});
Route::get('/gamer',function(){
    return view('gamer2');
});

Route::get('/forelse',function(){
    $name = ['jane','qqq','eeee'];
    return view('demos.forelse',compact('name'));
});

Route::get('/photo','\App\Http\Controllers\photoController@index');

Route::get('/Helloworld-test3','\App\Http\Controllers\photoController@index');
//123

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $guarded = [];


    //透過分類Id來尋找屬於該分類的商品
    public function scopeCgy( $query , $cgy_id )
    {
        if ($cgy_id != 'none') {
            return $query->where('cgy_id', $cgy_id);
        }else{
            return $query;
        }

    }

    public function scopeTag( $query , $tag_id)
    {
        if ($tag_id != 'none'){
            return $query->whereHas('tags',function($query) use ($tag_id){
                $query->where('id',$tag_id);
            });
        }else{
            return $query;
        }
    }

    //取得第一張圖
    public function getFirstPic(){
        if (isset($this->pics) && strlen($this->pics) > 0) {
            $pics = explode(',',$this->pics);
            return $pics[0];
        }else{
            return setting('site.item_default_pic');
        }
    }

    //取得商品圖片數量
    public function getPicsCount()
    {
        if (isset($this->pics) && strlen($this->pics) > 0) {
            $pics = explode(',',$this->pics);
            return count($pics);
        }else{
            return 0;
        }
    }

    //根據索引值來取得圖片
    public function getPicByIndex($index)
    {
        if (isset($this->pics) && strlen($this->pics) > 0) {
            $pics = explode(',',$this->pics);
            return $pics[$index];
        }else{
            return setting('site.item_default_pic');
        }
    }

    //回傳商品圖片路徑陣列
    public function getPicArray(){
        if (isset($this->pics) && strlen($this->pics) > 0) {
            $pics = explode(',',$this->pics);
            return $pics;
        }else{
            return [setting('site.item_default_pic')];
        }
    }

    //回傳商品特色內容陣列
    public function getCharsArray(){
        if (isset($this->chars) && strlen($this->chars) > 0) {
            $chars = explode(';',$this->chars);
            return $chars;
        }else{
            return null;
        }
    }

    public function getEnabled(){
        if ($this->enabled == '1') {
            return '是';
        }else{
            return '否';
        }
    }

    public function getPriceAttribute(){
        if (isset($this->price_new)){
            return $this->price_new;
        }else{
            return $this->price_og;
        }
    }

    public function cgy(){
        return $this->belongsTo(Cgy::class);
    }

    public function tags()
    {
        return $this->belongsToMany('App\Models\Tag')->withTimestamps();
    }

    // public function getBuyableIdentifier($options = null)
    // {
    //     return $this->id;
    // }

    // public function getBuyableDescription($options = null)
    // {
    //     return $this->title;
    // }

    // public function getBuyablePrice($options = null)
    // {
    //     return isset($this->price_new) ? $this->price_new : $this->price_og;
    // }
}

app/Models/User.php
<?php

namespace App\Models;

use Auth;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Notifications\Notifiable;
use Voyager;

class User extends \TCG\Voyager\Models\User
{
 use HasFactory, Notifiable;

 /**
  * The attributes that are mass assignable.
  *
  * @var array
  */
 protected $fillable = [
  'name',
  'email',
  'password',
 ];

 /**
  * The attributes that should be hidden for arrays.
  *
  * @var array
  */
 protected $hidden = [
  'password',
  'remember_token',
 ];

 /**
  * The attributes that should be cast to native types.
  *
  * @var array
  */
 protected $casts = [
  'email_verified_at' => 'datetime',
  'birthday'          => 'datetime',
  'email_verified_at' => 'datetime',
  'settings'          => 'array',
 ];

 public function getEnabled()
 {
  if ($this->enabled == '1') {
   return '是';
  } else {
   return '否';
  }
 }

 public function getPureDesc()
 {
  return strip_tags($this->desc);
 }

 public function getPicAttribute($value)
 {
  if (isset($value) && $value != null) {
   return Voyager::image($value);
  } else {
   return Voyager::image('users/avator.png');
  }
 }

 public function scopeSuper($query)
 {
  if (Auth::user()->role->name != 'super') {
   return $query->where('username', '!=', 'super');
  }
 }
}

resources/views/demos/about.blade.php
@extends('layouts.site')

@section('seo')
@isset($keywords)
<meta name="keywords" content="{{ __('About Us') }}">
@endisset
@isset($description)
<meta name="description" content="{{ setting('site.description') }}">
@endisset
@stop

@section('page_title'){{ __('About Us') }}@stop

@section('header_class') @stop

@section('body')
<!-- ======= About Us Section ======= -->
<section class="breadcrumbs">
    <div class="container">

        <div class="d-flex justify-content-between align-items-center">
            <h2>{{ __('About Us') }}</h2>
            <ol>
                <li><a href="{{ url('/') }}">{{ __('Home Page') }}</a></li>
                <li>{{ __('About Us') }}</li>
            </ol>
        </div>

    </div>
</section><!-- End About Us Section -->

<!-- ======= About Section ======= -->
<section class="about" data-aos="fade-up">
    <div class="container">

        <div class="row">
            <div class="col-lg-6">
                <img src="{{ $item_row1->getPicUrl() }}" class="img-fluid" alt="{{ $item_row1->alt }}">
            </div>
            <div class="col-lg-6 pt-4 pt-lg-0">
                <h3>{{ $item_row1->title }}</h3>
                {!! $item_row1->content !!}
            </div>
        </div>

    </div>
</section><!-- End About Section -->

<!-- ======= Facts Section ======= -->
<section class="facts section-bg" data-aos="fade-up">
    <div class="container">

        <div class="row counters">

            @foreach ($items_row2 as $item)
                <div class="col-lg-3 col-6 text-center">
                    <span data-toggle="counter-up">{{ $item->subtitle }}</span>
                    <p>{{ $item->title }}</p>
                </div>
            @endforeach

        </div>

    </div>
</section><!-- End Facts Section -->

<!-- ======= Our Skills Section ======= -->
<section class="skills" data-aos="fade-up">
    <div class="container">

        <div class="section-title">
            <h2>{{ $item_row3_top->title }}</h2>
            <p>{!! $item_row3_top->content !!}</p>
        </div>

        <div class="skills-content">

            @foreach ($items_row3 as $item)
                <div class="progress">
                    @php
                        if($item->subtitle > 70){
                            $color = 'bg-danger';
                        }else if($item->subtitle >= 60){
                            $color = 'bg-warning';
                        }else if($item->subtitle >= 40){
                            $color = 'bg-info';
                        }else{
                            $color = 'bg-success';
                        }
                    @endphp
                    <div class="progress-bar {{ $color }}" role="progressbar" aria-valuenow="{{ $item->subtitle }}"
                        aria-valuemin="0"
                        aria-valuemax="100">
                        <span class="skill">{{ $item->title }} <i class="val">{{ $item->subtitle }}%</i></span>
                    </div>
                </div>
            @endforeach
        </div>

    </div>
</section><!-- End Our Skills Section -->

<!-- ======= Tetstimonials Section ======= -->
<section class="testimonials" data-aos="fade-up">
    <div class="container">

        <div class="section-title">
            <h2>{{ $item_row4_top->title }}</h2>
            <p>{!! $item_row4_top->content !!}</p>
        </div>

        <div class="owl-carousel testimonials-carousel">

            @foreach ($items_row4 as $item)
                <div class="testimonial-item">
                    <img src="{{ $item->getPicUrl() }}" class="testimonial-img" alt="">
                    <h3>{{ $item->title }}</h3>
                    <h4>{{ $item->subtitle }}</h4>
                    <p>
                        <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                        {!! $item->content!!}
                        <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                    </p>
                </div>
            @endforeach

        </div>

    </div>
</section><!-- End Ttstimonials Section -->
@stop

resources/views/demos/article.blade.php
@extends('layouts.site')
@section('seo')
@isset($keywords)
<meta name="keywords" content="{{ $article->meta_keywords }}">
@endisset
@isset($description)
<meta name="description" content="{{ setting('site.description') }}">
@endisset
@stop
@section('page_title') {{ $article->title }} @stop

@section('header_class') @stop

@section('body')
<!-- ======= Blog Section ======= -->
<section class="blog" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
    <div class="container">

        <div class="row">

            <div class="col-lg-8 entries">

                <article class="entry entry-single">
                    <div class="entry-img">
                        <img src="{{ $article->getPicUrl() }}" alt="{{ $article->title }}" class="img-fluid">
                    </div>

                    <h2 class="entry-title">
                        {{ $article->title }}
                    </h2>

                    <div class="entry-meta">
                        <ul>
                            <li class="d-flex align-items-center"><i class="icofont-user"></i>
                                {{ $article->user->name }}
                            </li>
                            <li class="d-flex align-items-center"><i class="icofont-wall-clock"></i>
                                {{ $article->created_at->diffForHumans() }}
                            </li>
                            <li class="d-flex align-items-center"><i class="icofont-comment"></i>
                                {{ $article->commentQty }}
                            </li>
                        </ul>
                    </div>

                    <div class="entry-content">
                        <p>
                            {!! $article->content !!}
                        </p>

                    </div>

                    <div class="entry-footer clearfix">
                        <div class="float-left">
                            <i class="icofont-folder"></i>
                            <ul class="cats">
                                <li><a href="{{ url('/demo/articles/'.$article->cgy->id) }}">{{ $article->cgy->title }}</a>
                                </li>
                            </ul>

                            <i class="icofont-tags"></i>
                            <ul class="tags">
                                @foreach ($article->tagsList as $key => $value)
                                    <li><a href="#">{{ $value }}</a></li>
                                @endforeach
                                <li><a href="#">Tips</a></li>
                                <li><a href="#">Marketing</a></li>
                            </ul>
                        </div>

                        <div class="float-right share">
                            <a href="" title="Share on Twitter"><i class="icofont-twitter"></i></a>
                            <a href="" title="Share on Facebook"><i class="icofont-facebook"></i></a>
                            <a href="" title="Share on Instagram"><i class="icofont-instagram"></i></a>
                        </div>

                    </div>

                </article><!-- End blog entry -->

                <div class="blog-author clearfix">
                    <img src="{{ Voyager::image($article->user->avatar) }}" class="rounded-circle float-left" alt="">
                    <h4>{{ $article->user->name }}</h4>
                    <div class="social-links">
                        <a href="https://twitters.com/#"><i class="icofont-twitter"></i></a>
                        <a href="https://facebook.com/#"><i class="icofont-facebook"></i></a>
                        <a href="https://instagram.com/#"><i class="icofont-instagram"></i></a>
                    </div>
                    <p>
                        Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus accusantium. Quas
                        repellat
                        voluptatem officia numquam sint aspernatur voluptas. Esse et accusantium ut unde voluptas.
                    </p>
                </div><!-- End blog author bio -->

                <div class="blog-comments">

                    <h4 class="comments-count"> {{$article->comments()->count() .' '. __('Comments') }}</h4>

                    @foreach ($article->comments as $comment)
                        <div id="comment-{{ $comment->id }}" class="comment clearfix">
                            <img src="{{ $comment->user->pic }}" class="comment-img  float-left" alt="">
                            <h5><a href="">{{ $comment->user->name }}</a> <a href="#" class="reply"><i class="icofont-reply"></i>
                                    {{ __('Reply') }}</a></h5>
                            <time datetime="2020-01-01">{{ $comment->created_at }}</time>
                            <p>
                                {!! $comment->content !!}
                            </p>
                        </div><!-- End comment #1 -->
                    @endforeach

                    <div class="reply-form">
                        <h4>{{ __('Reply a message') }}</h4>
                        <p>{{ __('Your email address will not be published. Required fields are marked *') }} </p>
                        <form action="">
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <input name="name" type="text" class="form-control"
                                        placeholder="{{ __('Your Name*') }}">
                                </div>
                                <div class="col-md-6 form-group">
                                    <input name="email" type="text" class="form-control"
                                        placeholder="{{ __('Your Email*') }}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col form-group">
                                    <input name="website" type="text" class="form-control"
                                        placeholder="{{ __('Your Website') }}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col form-group">
                                    <textarea name="comment" class="form-control"
                                        placeholder="{{ __('Your Comment*') }}"></textarea>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">{{ __('Post Comment') }}</button>
                        </form>
                    </div>

                </div><!-- End blog comments -->

            </div><!-- End blog entries list -->

            <div class="col-lg-4">
                <div class="sidebar">

                    <h3 class="sidebar-title">{{ __('Search') }}</h3>
                    <div class="sidebar-item search-form">
                        <form action="">
                            <input type="text">
                            <button type="submit"><i class="icofont-search"></i></button>
                        </form>
                    </div><!-- End sidebar search formn-->

                    <h3 class="sidebar-title">{{ __('Category') }}</h3>
                    <div class="sidebar-item categories">
                        <ul>
                            @foreach ($cgys as $cgy)
                            <li><a href="{{ url('/demo/articles/'.$cgy->id) }}">{{ $cgy->title }}
                                    <span>({{ $cgy->articles()->count() }})</span></a></li>
                            @endforeach
                        </ul>

                    </div><!-- End sidebar categories-->
                    @if($articles_feature != null && count($articles_feature) > 0)
                    <h3 class="sidebar-title">{{ __('Feature Articles') }}</h3>
                    <div class="sidebar-item recent-posts">
                        @foreach ($articles_feature as $article)
                        <div class="post-item clearfix">
                            <img src="{{ $article->getPicUrl() }}" alt="">
                            <h4><a href="{{ '/demo/articles/' . $article->id }}">{{ $article->title }}</a></h4>
                            <time datetime="2020-01-01">{{ $article->created_at->diffForHumans() }}</time>
                        </div>
                        @endforeach
                    </div><!-- End sidebar recent posts-->
                    @endif

                    <h3 class="sidebar-title">{{ __('Tags') }}</h3>
                    <div class="sidebar-item tags">
                        <ul>
                            @foreach ($tags as $tag)
                            <li><a href="#">{{ $tag->title }}</a></li>
                            @endforeach
                        </ul>

                    </div><!-- End sidebar tags-->

                </div><!-- End sidebar -->

            </div><!-- End blog sidebar -->

        </div><!-- End .row -->

    </div><!-- End .container -->

</section><!-- End Blog Section -->
@stop

resources/views/demos/articles.blade.php
@extends('layouts.site')
@section('seo')
@isset($keywords)
<meta name="keywords" content="{{ $cgy->title }}">
@endisset
@isset($description)
<meta name="description" content="{{ setting('site.description') }}">
@endisset
@stop
@section('page_title') {{ $cgy->title }} @stop

@section('header_class') @stop

@section('body')
<!-- ======= Blog Section ======= -->
<section class="blog" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
    <div class="container">

        <div class="row">

            <div class="col-lg-8 entries">

                @isset($articles)
                @foreach ($articles as $article)
                <article class="entry">

                    <div class="entry-img">
                        <img src="{{ $article->getPicUrl() }}" alt="{{ $article->title }}" class="img-fluid">
                    </div>

                    <h2 class="entry-title">
                        <a href="{{ '/demo/article/' . $article->id }}">
                            {{ $article->title }}
                        </a>
                    </h2>

                    <div class="entry-meta">
                        <ul>
                            <li class="d-flex align-items-center"><i class="icofont-user"></i>
                                {{ $article->user->name }}
                            </li>
                            <li class="d-flex align-items-center"><i class="icofont-wall-clock"></i>
                                {{ $article->created_at->diffForHumans() }}
                            </li>
                            <li class="d-flex align-items-center"><i class="icofont-comment"></i>
                                {{ $article->commentQty }}
                            </li>
                        </ul>
                    </div>

                    <div class="entry-content">
                        <p>
                            {!! $article->content_small !!}
                        </p>
                        <div class="read-more">
                            <a href="{{ '/demo/article/' . $article->id }}">{{ __('Read More') }}</a>
                        </div>
                    </div>

                </article><!-- End blog entry -->
                @endforeach
                @endisset

                @isset($articles)
                    <div class="blog-pagination">
                        {!! $articles->links() !!}
                    </div>
                @endisset

            </div><!-- End blog entries list -->

            <div class="col-lg-4">
                <div class="sidebar">

                    <h3 class="sidebar-title">{{ __('Search') }}</h3>
                    <div class="sidebar-item search-form">
                        <form action="">
                            <input type="text">
                            <button type="submit"><i class="icofont-search"></i></button>
                        </form>
                    </div><!-- End sidebar search formn-->

                    <h3 class="sidebar-title">{{ __('Category') }}</h3>
                    <div class="sidebar-item categories">
                        <ul>
                            @foreach ($cgys as $cgy)
                                <li><a href="{{ url('/demo/articles/'.$cgy->id) }}">{{ $cgy->title }} <span>({{ $cgy->articles()->count() }})</span></a></li>
                            @endforeach
                        </ul>

                    </div><!-- End sidebar categories-->
                    @if($articles_feature != null && count($articles_feature) > 0)
                        <h3 class="sidebar-title">{{ __('Feature Articles') }}</h3>
                        <div class="sidebar-item recent-posts">
                            @foreach ($articles_feature as $article)
                                <div class="post-item clearfix">
                                    <img src="{{ $article->getPicUrl() }}" alt="">
                                    <h4><a href="{{ '/demo/articles/' . $article->id }}">{{ $article->title }}</a></h4>
                                    <time datetime="2020-01-01">{{ $article->created_at->diffForHumans() }}</time>
                                </div>
                            @endforeach
                        </div><!-- End sidebar recent posts-->
                    @endif

                    <h3 class="sidebar-title">{{ __('Tags') }}</h3>
                    <div class="sidebar-item tags">
                        <ul>
                            @foreach ($tags as $tag)
                                <li><a href="#">{{ $tag->title }}</a></li>
                            @endforeach
                        </ul>

                    </div><!-- End sidebar tags-->

                </div><!-- End sidebar -->

            </div><!-- End blog sidebar -->

        </div><!-- End .row -->

    </div><!-- End .container -->

</section><!-- End Blog Section -->
@stop

resources/views/demos/forelse.blade.php
{{ $tel }}

<ul>
    @forelse ($name as $name)
    <li>{{ $name }} {{ $loop -> iteration }} </li>
@empty
    沒東西
@endforelse
</ul>

resources/views/demos/portfolioDetail.blade.php
@extends('layouts.site')

@section('seo')
@isset($keywords)
<meta name="keywords" content="{{ $media->title }}">
@endisset
@isset($description)
<meta name="description" content="{{ setting('site.description') }}">
@endisset
@stop

@section('page_title'){{ $media->title }}@stop

@section('header_class') @stop

@section('body')
<!-- ======= Portfolio Detail Section ======= -->
<section class="breadcrumbs">
    <div class="container">

        <div class="d-flex justify-content-between align-items-center">
            <h2>{{ $media->title }}</h2>
            <ol>
                <li><a href="{{ url('/') }}">{{ __('Home Page') }}</a></li>
                <li>{{ $media->title }}</li>
            </ol>
        </div>

    </div>
</section><!-- End Portfolio Detail Section -->

<!-- ======= Portfolio Details Section ======= -->
<section class="portfolio-details">
    <div class="container">

        <div class="portfolio-details-container">

            <div class="owl-carousel portfolio-details-carousel">
                @foreach ($media->getPicsArray() as $pic)
                    <img src="{{ $pic }}" class="img-fluid" alt="">
                @endforeach
            </div>

            <div class="portfolio-info">
                <h3>{{ $media->detail_title }}</h3>
                <ul>
                    <li><strong>{{ __('Category') }}</strong>: {{ $media->cgyName }}</li>
                    <li><strong>{{ __('Client') }}</strong>: {{ $media->client }}</li>
                    <li><strong>{{ __('Project Date') }}</strong>:
                        {{ date('Y/m/d', strtotime($media->project_date)) }}
                    </li>
                    <li><strong>{{ __('Project URL') }}</strong>: <a href="{{ $media->url }}">{{ $media->url }}</a></li>
                </ul>
            </div>

        </div>

        <div class="portfolio-description">
            <h2>{{ $media->detail_title }}</h2>
            <p>
                {!! $media->content !!}
            </p>
        </div>
    </div>
</section><!-- End Portfolio Details Section -->

@stop

resources/views/demos/services.blade.php
@extends('layouts.site')

@section('seo')
@isset($keywords)
<meta name="keywords" content="{{ __('Our Services')}}">
@endisset
@isset($description)
<meta name="description" content="{{ setting('site.description') }}">
@endisset
@stop

@section('page_title'){{ __('Our Services')}} @stop

@section('header_class') @stop

@section('body')
<!-- ======= Our Services Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>{{ __('Our Services')}}</h2>
          <ol>
            <li><a href="{{ url('/') }}">{{ __('Home Page') }}</a></li>
            <li>{{ __('Our Services') }}</li>
          </ol>
        </div>

      </div>
    </section><!-- End Our Services Section -->

    <section class="services">
        <div class="container">

            <div class="row">
                @foreach ($items_row1 as $item)
                    <div class="col-md-6 col-lg-3 d-flex align-items-stretch" data-aos="fade-up">
                        <div class="icon-box icon-box-{{ $item->title_color }}">
                            <div class="icon"><i class="bx {{ $item->icon }}"></i></div>
                            <h4 class="title" style="color:{{ $item->title_color }}"><a href="{{ $item->url }}">{!! $item->title !!}</a></h4>
                            <p class="description">{!! $item->content !!}</p>
                        </div>
                    </div>
                @endforeach

            </div>

        </div>
    </section><!-- End Services Section -->

    <!-- ======= Row2 Section ======= -->
    <section class="why-us section-bg" data-aos="fade-up" date-aos-delay="200">
        <div class="container">

            <div class="row">
                <div class="col-lg-6 video-box">
                    <img src="{{ $item_row2_video->getPicUrl() }}" class="img-fluid" alt="{{ $item_row2_video->alt }}">
                    <a href="{{ $item_row2_video->video }}" class="venobox play-btn mb-4"
                        data-vbtype="video" data-autoplay="true"></a>
                </div>

                <div class="col-lg-6 d-flex flex-column justify-content-center p-5">
                    @foreach ($items_row2 as $item)
                        <div class="icon-box">
                            <div class="icon"><i class="bx {{ $item->icon }}"></i></div>
                            <h4 class="title"><a href="">{{ $item->title }}</a></h4>
                            <p class="description">{{ $item->content }}</p>
                        </div>
                    @endforeach

                </div>
            </div>

        </div>
    </section><!-- End Row2 Section -->

    <!-- ======= Service Details Section ======= -->
    <section class="service-details">
      <div class="container">

        <div class="row">
          @foreach($items_row3 as $item) 
            <div class="col-md-6 d-flex align-items-stretch" data-aos="fade-up">
            <div class="card">
              <div class="card-img">
                <img src="{{ $item->getPicUrl() }}" alt="{{ $item->alt }}">
              </div>
              <div class="card-body">
                <h5 class="card-title"><a href="#">{{ $item->title }}</a></h5>
                <p class="card-text">{!! $item->content !!}</p>
                <div class="read-more"><a href="{{ $item->url }}"><i class="icofont-arrow-right"></i> {{__('Read More')}}</a></div>
              </div>
            </div>
          </div>
          @endforeach
        </div>

      </div>
    </section><!-- End Service Details Section -->

    <!-- ======= Pricing Section ======= -->
    <section class="pricing section-bg" data-aos="fade-up">
      <div class="container">

        <div class="section-title">
          <h2>{{ $item_price_top->title }}</h2>
          <p>{!! $item_price_top->content !!}</p>
        </div>

        <div class="row no-gutters">
          @foreach($items_prices as $item)
            <div class="col-lg-4 box">
                <h3>{{ $item->title }}</h3>
                <h4>${{ $item->price }}<span>{{ $item->priceUnit }}</span></h4>
                {!! $item->content !!}
                <a href="{{ $item->url }}" class="get-started-btn">{{ __('Get Start') }}</a>
            </div>
          @endforeach
        </div>

      </div>
    </section><!-- End Pricing Section -->
@stop